language: node_js
install:
  - npm install -g codecov
  - npm install
script:
  - npm test
  - codecov
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
